name: Release published
on: [push, pull_request]

jobs:
  build:
    runs-on:
      - ubuntu-latest
      strategy:
        matrix:
          java: [8, 8.0.x, 9.0.x, 11.0.x, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}

      - name: Run Codecov
          uses: codecov/codecov-action@v1
